### ISSUE TITLE
stream.transform afterTransform condition - wrong sign?

### ISSUE THREAD

**Issue by bartwalczak** [iojs/readable-stream#128]
Line 108 in `lib/_stream_transform.js` says:

```  
if (rs.needReadable || rs.length < rs.highWaterMark) {
    stream._read(rs.highWaterMark);
}
```

However, the condition never reaches `stream._read`, if `fs.needReadable` is actually false and just hangs in there.

I believe it should say:
``` 
if (rs.needReadable || rs.length >= rs.highWaterMark) { 
...
}
```

At least it fixed my issue.

**Comment by calvinmetcalf** [comment]
so  rs.length is the amount of stuff currently in the buffer of stuff already read so this conditional says if our buffer has less stuff in it then our high water mark (aka max buffer size) then read to fill the buffer.

basically data from our source gets but into a buffer and as stuff reads from the stream the buffer is emptied, this code is designed so that if the buffer gets to full we stop reading from the source until the data gets read out of the buffer.

I'd wager that your issue is that nothing is consuming your stream, like maybe you are piping it to a transform stream but then nothing is consuming that (I did this once and it took me 4 hours to track it down, switch the transform stream to not emit anything and it suddenly worked).

**Comment by bartwalczak** [comment]
Possibly. 

How do I switch the transform stream to not emit anything?

**Comment by calvinmetcalf** [comment]
so what I had been doing was

```
readableStream.pipe(transformStream).pipe(otherTransformStream);
```

when what I really wanted was

```js
readableStream.pipe(transformStream).pipe(writableStream);
```

but it's really going to depend on your code and how it's set up, you should just make sure that if you are piping to things whatever is last in the pipe chain is not creating more data (feel free to post your code to a gist)

**Comment by bartwalczak** [comment]
Thanks a lot. That helped.
